language: julia

os:
  - linux

julia:
  - 1.0

notifications:
    email: false

#coveralls: true
#after_success:
#  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
