name = "Hello"
uuid = "74db4048-4eb6-11e9-1e38-93c4da6edecd"
authors = ["Weiwei Wang <wangweiwei@ahu.edu.cn>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
