name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Build docs
      run: |
        julia --color=yes --project=docs/ docs/make.jl
